routes/web.php
<?php


Route::group(['middleware' => 'check_user_profile'], function() {
    Route::get('/', 'MainController@index')->name('index');

    Route::get('/feedback', 'FeedbackController@index');
    Route::post('/feedback', 'FeedbackController@send');

    Route::group(['middleware' => 'auth'], function() {

        Route::post('profile/edit', 'ProfileController@edit');
        Route::resource('profile', 'ProfileController');
//        Route::get('profile/{id}', 'ProfileController@show')->name('profile');

//        Route::post('profile', 'ProfileController@update');

        Route::get('search', 'SearchController@search')->name('search');
    });
});

Route::group(['prefix' => 'auth', 'as' => 'auth.'], function() {
    Route::get('login', 'AuthController@login')->name('login');
    Route::post('login', 'AuthController@login');

    Route::get('register', 'AuthController@register')->name('register')->middleware('guest');
    Route::post('register', 'AuthController@register');

    Route::get('logout', 'AuthController@logout')
        ->name('logout')->middleware('auth');

    Route::post('ulogin', 'AuthController@ulogin')
        ->name('ulogin');

    Route::get('confirm_email/{user_id}/{code}', 'AuthController@confirmEmail')
        ->name('confirm_email');

    Route::group(['middleware' => 'auth'], function() {
        Route::get('complete', 'AuthController@completeRegistration')
            ->name('complete');
        Route::post('complete', 'AuthController@completeRegistration');
    });

});

Route::get('language/{code}', 'LanguageController@setLanguage')->name('language');

// TODO make it available to admins only

Route::middleware('isAdmin')->group(function(){

    Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {

        Route::get('blog/categories/{id}/delete', 'Admin\BlogController@deleteCategory');
        Route::post('blog/categories/{id}/update', 'Admin\BlogController@updateCategory');
        Route::get('blog/categories/{id}/edit', 'Admin\BlogController@editCategory');
        Route::post('blog/categories', 'Admin\BlogController@saveCategory');
        Route::resource('blog', 'Admin\BlogController');
        Route::resource('permissions', 'Admin\PermissionsController');
        Route::resource('roles', 'Admin\RolesController');
        Route::resource('users', 'Admin\UsersController');

        Route::post('menu/item-delete', 'Admin\MenuController@deleteItem');
        Route::post('menu/update-item', 'Admin\MenuController@updateItem');
        Route::post('menu/save-item', 'Admin\MenuController@saveItem');
        Route::resource('menu', 'Admin\MenuController');

        Route::resource('pages', 'Admin\\PagesController');

        Route::get('', 'Admin\\HomeController@index')->name('index');

        Route::resource('categories', 'Admin\PropertyCategoriesController');

        Route::group(['prefix' => 'properties', 'as' => 'property.'], function() {
            Route::get('', 'Admin\\PropertiesController@index')->name('index');
            Route::match(['get', 'post'], 'create', 'Admin\\PropertiesController@create')->name('create');
            Route::get('{id}', 'Admin\\PropertiesController@show')->name('show');
            Route::post('{id}', 'Admin\\PropertiesController@update')->name('update');

            Route::post('value/{id}', 'Admin\\PropertiesController@updateValue')->name('update-value');
            Route::match(['get', 'post'], '{id}/value', 'Admin\\PropertiesController@createValue')->name('create-value');

            Route::get('value-translation/{id}', 'Admin\\PropertiesController@showValueTranslation')->name('show-value-translation');
            Route::post('value-translation/{id}', 'Admin\\PropertiesController@updateValueTranslation')->name('update-value-translation');
            Route::match(['get', 'post'], '{id}/value-translation/{languageId}', 'Admin\\PropertiesController@createValueTranslation')->name('create-value-translation');
        });

    });

});

Route::any('/messages', 'MessagesController@pipes')->name('chat');
Route::any('/messages/delete', 'MessagesController@delMessage')->name('deleteChatMessage');
Route::any('/messages/edit', 'MessagesController@editMessage')->name('editChatMessage');

Route::any('/messages/favorite/', 'MessagesController@status')->name('favMessage');
//Route::any('/messages/blacklist', 'MessagesController@status')->name('blMessage');
Route::any('/messages/upload', 'MessagesController@upload')->name('chatImage');

Route::get('/messages/update/{user}/{pipe}', function($user, $pipe){
    \App\Http\Controllers\MessagesController::setPipeTime($user,$pipe);
});

resources/views/partials/header/index.blade.php
<div class="g-header">
    <div class="container">
        <div class="g-header__top">
            <a href="index.html"><img src="img/logo.png" alt="поиск содержанок и спонсоров"></a>
            <nav class="g-header__nav">
                <ul>
                    <li><a href="#" title="">войти</a></li>
                    <li><a class="btn-link" href="#" title="">Регистрация</a></li>
                </ul>
            </nav>
        </div>
        <div class="g-header__bottom">
            <div class="g-header__bottom-info">
                <h1 class="text-line">Знакомства <br>
                    для успешных мужчин</h1>
                <div class="title">Sweet life – делаем расчет
                    <br> в отношениях выгодным
                </div>
            </div>
            <div class="form-wrap">
                <div class="b-form form">
                    <div class="b-form__bg"></div>
                    <form>
                        <div class="top">
                            <div class="title">Найдите свою
                                <br> вторую половинку</div>
                            <div class="form-group">
                                <label>Кого вы ищете</label>
                                <select class="select-custom" placeholder="Девушку">
                                    <option value="0">Девушку</option>
                                    <option value="1">Парня</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Введите город</label>
                                <input type="text" class="form-control" placeholder="Город">
                            </div>
                            <div class="form-group form-group__age">
                                <label>Выберите возраст</label>
                                <input class="age-slider" type="slider">
                            </div>
                            <div class="btn-wrap">
                                <button type="submit" class="btn-link btn-link__accent">Искать</button>
                            </div>
                        </div>
                        <div class="bottom">
                            <label>
                                <input type="checkbox" checked="">
                                <span class="icon"></span>
                                <span class="checkbox__title">Запомнить мой выбор</span>
                            </label>
                            <a href="#" class="checkbox__help fa fa-question-circle"></a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/partials/header/main.blade.php
<header class="header">
    <div class="header__top-wrap">
        <div class="container">
            <div class="header__top">
                <a class="logo" href="index.html"><img src="img/logo-clean.png" alt="поиск содержанок и спонсоров"></a>
                <nav class="header__nav">
                    <ul>
                        <li><a href="#" title="">выход <i class="icon icon-out"></i></a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <div class="header__bottom-wrap">
        <div class="container">
            <div class="header__bottom">
                <div class="mob-nav visible-xs visible-sm">
                    <a class="fa fa-bars" href="#menu"></a>
                    <nav class="header__menu" id="menu">
                        <ul>
                            <li><a href="" title="">Поиск</a></li>
                            <li><a href="" title="">Кто смотрел</a></li>
                            <li><a href="" title="">Рассылка</a></li>
                            <li><a href="" title="">Сообщения</a></li>
                        </ul>
                    </nav>
                </div>
                <nav class="header__menu hidden-xs hidden-sm" id="menu">
                    <ul>
                        <li><a href="" title="">Поиск</a></li>
                        <li><a href="" title="">Кто смотрел</a></li>
                        <li><a href="" title="">Рассылка</a></li>
                        @if (Auth::user())
                            <li><a href="{{ route("profile.index") }}">Профиль</a></li>
                            <li><a href="{{ route("chat") }}">Сообщения</a></li>
                        @endif
                    </ul>
                    {{--<ul class="nav navbar-nav navbar-right">--}}
                    {{--<select id='language'>--}}
                    {{--@foreach ($languages as $l)--}}
                    {{--<option value="{{ $l->code }}" {{ $language == $l->code ? "selected" : "" }}>{{ $l->code }}</option>--}}
                    {{--@endforeach--}}
                    {{--</select>--}}
                    {{--@if (Auth::user())--}}
                    {{--<li>--}}
                    {{--<form method='POST' action='{{ route('auth.logout') }}'>--}}
                    {{--{{ csrf_field() }}--}}
                    {{--<input type="submit" value="{{ Translation::translateKey('LOGOUT') }}"><span--}}
                    {{--class="glyphicon glyphicon-log-in"></span> </input>--}}
                    {{--</form>--}}
                    {{--</li>--}}
                    {{--@else--}}
                    {{--<li><a href="{{ route('auth.login') }}"><span--}}
                    {{--class="glyphicon glyphicon-log-out"></span> {{ Translation::translateKey('LOGIN') }}--}}
                    {{--</a></li>--}}
                    {{--@endif--}}
                    {{--</ul>--}}
                </nav>
                <nav class="header__action-panel">
                    @if(Auth::check())
                        <ul>
                            <li><a href="" title="">Счет: <span>100.00</span> руб.</a></li>
                            <li class="avatar__wrap"><a href="" title="">
							<span class="avatar" style="background-image: url({{Auth::user()->getMainPhoto()}})">
							{{--<img src="{{Auth::user()->getMainPhoto()}}" alt="">--}}
                            </span>
                                    <span class="username">{{Auth::user()->name}}</span>
                                </a></li>
                            <li><a class="btn-buy" href="" title="">Купить премиум</a></li>
                        </ul>
                    @endif
                </nav>
            </div>
        </div>
    </div>
</header>