routes/web.php
<?php


Route::group(['middleware' => 'check_user_profile'], function() {
    Route::get('/', 'MainController@index')->name('index');

    Route::get('/feedback', 'FeedbackController@index');
    Route::post('/feedback', 'FeedbackController@send');

    Route::group(['middleware' => 'auth'], function() {

        Route::post('profile/edit', 'ProfileController@edit');
        Route::resource('profile', 'ProfileController');
//        Route::get('profile/{id}', 'ProfileController@show')->name('profile');

//        Route::post('profile', 'ProfileController@update');

        Route::get('search', 'SearchController@search')->name('search');
    });
});

Route::group(['prefix' => 'auth', 'as' => 'auth.'], function() {
    Route::get('login', 'AuthController@login')->name('login');
    Route::post('login', 'AuthController@login');

    Route::get('register', 'AuthController@register')->name('register')->middleware('guest');
    Route::post('register', 'AuthController@register');

    Route::get('logout', 'AuthController@logout')
        ->name('logout')->middleware('auth');

    Route::post('ulogin', 'AuthController@ulogin')
        ->name('ulogin');

    Route::get('confirm_email/{user_id}/{code}', 'AuthController@confirmEmail')
        ->name('confirm_email');

    Route::group(['middleware' => 'auth'], function() {
        Route::get('complete', 'AuthController@completeRegistration')
            ->name('complete');
        Route::post('complete', 'AuthController@completeRegistration');
    });

});

Route::get('language/{code}', 'LanguageController@setLanguage')->name('language');

// TODO make it available to admins only

Route::middleware('isAdmin')->group(function(){

    Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {

        Route::get('blog/categories/{id}/delete', 'Admin\BlogController@deleteCategory');
        Route::post('blog/categories/{id}/update', 'Admin\BlogController@updateCategory');
        Route::get('blog/categories/{id}/edit', 'Admin\BlogController@editCategory');
        Route::post('blog/categories', 'Admin\BlogController@saveCategory');
        Route::resource('blog', 'Admin\BlogController');
        Route::resource('permissions', 'Admin\PermissionsController');
        Route::resource('roles', 'Admin\RolesController');
        Route::resource('users', 'Admin\UsersController');

        Route::post('menu/item-delete', 'Admin\MenuController@deleteItem');
        Route::post('menu/update-item', 'Admin\MenuController@updateItem');
        Route::post('menu/save-item', 'Admin\MenuController@saveItem');
        Route::resource('menu', 'Admin\MenuController');

        Route::resource('pages', 'Admin\\PagesController');

        Route::get('', 'Admin\\HomeController@index')->name('index');

        Route::resource('categories', 'Admin\PropertyCategoriesController');

        Route::group(['prefix' => 'properties', 'as' => 'property.'], function() {
            Route::get('', 'Admin\\PropertiesController@index')->name('index');
            Route::match(['get', 'post'], 'create', 'Admin\\PropertiesController@create')->name('create');
            Route::get('{id}', 'Admin\\PropertiesController@show')->name('show');
            Route::post('{id}', 'Admin\\PropertiesController@update')->name('update');

            Route::post('value/{id}', 'Admin\\PropertiesController@updateValue')->name('update-value');
            Route::match(['get', 'post'], '{id}/value', 'Admin\\PropertiesController@createValue')->name('create-value');

            Route::get('value-translation/{id}', 'Admin\\PropertiesController@showValueTranslation')->name('show-value-translation');
            Route::post('value-translation/{id}', 'Admin\\PropertiesController@updateValueTranslation')->name('update-value-translation');
            Route::match(['get', 'post'], '{id}/value-translation/{languageId}', 'Admin\\PropertiesController@createValueTranslation')->name('create-value-translation');
        });

    });

});

Route::any('/messages', 'MessagesController@pipes')->name('chat');
Route::any('/messages/delete', 'MessagesController@delMessage')->name('deleteChatMessage');
Route::any('/messages/edit', 'MessagesController@editMessage')->name('editChatMessage');

Route::any('/messages/favorite/', 'MessagesController@status')->name('favMessage');
//Route::any('/messages/blacklist', 'MessagesController@status')->name('blMessage');
Route::any('/messages/upload', 'MessagesController@upload')->name('chatImage');

Route::get('/messages/update/{user}/{pipe}', function($user, $pipe){
    \App\Http\Controllers\MessagesController::setPipeTime($user,$pipe);
});

resources/views/admin/modules/footer.blade.php
<footer class="m-grid__item		m-footer ">
    <div class="m-container m-container--fluid m-container--full-height m-page__container">
        <div class="m-stack m-stack--flex-tablet-and-mobile m-stack--ver m-stack--desktop">
            <div class="m-stack__item m-stack__item--left m-stack__item--middle m-stack__item--last">
							<span class="m-footer__copyright">
								2017 &copy; Metronic theme by
								<a href="#" class="m-link">
									Keenthemes
								</a>
							</span>
            </div>
            <div class="m-stack__item m-stack__item--right m-stack__item--middle m-stack__item--first">
                <ul class="m-footer__nav m-nav m-nav--inline m--pull-right">
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
										<span class="m-nav__link-text">
											About
										</span>
                        </a>
                    </li>
                    <li class="m-nav__item">
                        <a href="#"  class="m-nav__link">
										<span class="m-nav__link-text">
											Privacy
										</span>
                        </a>
                    </li>
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
										<span class="m-nav__link-text">
											T&C
										</span>
                        </a>
                    </li>
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
										<span class="m-nav__link-text">
											Purchase
										</span>
                        </a>
                    </li>
                    <li class="m-nav__item m-nav__item">
                        <a href="#" class="m-nav__link" data-toggle="m-tooltip" title="Support Center" data-placement="left">
                            <i class="m-nav__link-icon flaticon-info m--icon-font-size-lg3"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

resources/views/admin/modules/sidebar.blade.php
<button class="m-aside-left-close  m-aside-left-close--skin-dark " id="m_aside_left_close_btn">
    <i class="la la-close"></i>
</button>
<div id="m_aside_left" class="m-grid__item	m-aside-left  m-aside-left--skin-dark ">
    <!-- BEGIN: Aside Menu -->
    <div    id="m_ver_menu"
            class="m-aside-menu  m-aside-menu--skin-dark m-aside-menu--submenu-skin-dark "
            data-menu-vertical="true"
            data-menu-scrollable="false" data-menu-dropdown-timeout="500"
    >
        <ul class="m-menu__nav  m-menu__nav--dropdown-submenu-arrow ">
            {{--<li class="m-menu__item " aria-haspopup="true">--}}
                {{--<a href="{{ route("admin.property.index") }}" class="m-menu__link ">--}}
                    {{--<i class="m-menu__link-icon flaticon-layers"></i>--}}
                    {{--<span class="m-menu__link-text">{{ Translation::translateKey('PROPERTIES') }}</span>--}}
                {{--</a>--}}
            {{--</li>--}}

            <li class="m-menu__item m-menu__item--submenu" aria-haspopup="true" data-menu-submenu-toggle="hover">
                <a href="#" class="m-menu__link m-menu__toggle">
                    <i class="m-menu__link-icon flaticon-users"></i>
                    <span class="m-menu__link-text">Пользователи</span>
                    <i class="m-menu__ver-arrow la la-angle-right"></i>
                </a>
                <div class="m-menu__submenu">
                    <span class="m-menu__arrow"></span>
                    <ul class="m-menu__subnav">
                        <li class="m-menu__item " aria-haspopup="true">
                            <a href="{{url('admin/users')}}" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot">
                                    <span></span>
                                </i>
                                <span class="m-menu__link-text">
                                    Пользователи
                                </span>
                            </a>
                        </li>
                        <li class="m-menu__item " aria-haspopup="true">
                            <a href="{{url('admin/roles')}}" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot">
                                    <span></span>
                                </i>
                                <span class="m-menu__link-text">
                                    Роли
                                </span>
                            </a>
                        </li>
                        <li class="m-menu__item" aria-haspopup="true">
                            <a href="{{url('admin/permissions')}}" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot">
                                    <span></span>
                                </i>
                                <span class="m-menu__link-text">
                                    Права
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>

            <li class="m-menu__item m-menu__item--submenu" aria-haspopup="true" data-menu-submenu-toggle="hover">
                <a href="#" class="m-menu__link m-menu__toggle">
                    <i class="m-menu__link-icon flaticon-web"></i>
                    <span class="m-menu__link-text">Контент</span>
                    <i class="m-menu__ver-arrow la la-angle-right"></i>
                </a>
                <div class="m-menu__submenu">
                    <span class="m-menu__arrow"></span>
                    <ul class="m-menu__subnav">
                        <li class="m-menu__item" aria-haspopup="true">
                            <a href="{{url('admin/pages')}}" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot"></i>
                                <span class="m-menu__link-text">
                                    Страницы
                                </span>
                            </a>
                        </li>
                        <li class="m-menu__item" aria-haspopup="true">
                            <a href="{{url('admin/blog')}}" class="m-menu__link ">
                                <i class="m-menu__link-bullet m-menu__link-bullet--dot"></i>
                                <span class="m-menu__link-text">
                                    Блог
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>

            <li class="m-menu__item m-menu__item--submenu" aria-haspopup="true">
                <a href="{{url('admin/menu')}}" class="m-menu__link">
                    <i class="m-menu__link-icon flaticon-squares-2"></i>
                    <span class="m-menu__link-text">Меню</span>
                </a>
            </li>

        </ul>
    </div>
    <!-- END: Aside Menu -->
</div>